### ISSUE TITLE
pd.append depreciated

### ISSUE THREAD

**Issue by mattwood-astro** [lucashusted/pystout#6]
When running recently Python threw warning that pd.append() is depreciated, and to switch to .append.  If you replace the current line (near bottom of file, commented out here) with the second line, the warning message disappears and the output is identical.

            #options = options.append(pd.DataFrame([r],index=[value]))
            options = pd.concat([options,pd.DataFrame([r],index=[value])])

As always, thanks for a very useful package!

**Comment by masact** [comment]
Yes, confirmed: I was getting "AttributeError: 'DataFrame' object has no attribute 'append'" and found this post. Thanks for the great package and the fix!

**Comment by mwood7** [comment]
Hi, Lucas:
It looks like you updated your code to include concat instead of append, but when I do pip install pystout for some reason I'm getting the old version (?).  We're writing a book where we point the readers to pystout, but does pip install not pull directly from your GitHub (?).  I don't know anything about how that works.

Cheers, and thanks again for a very useful and easy-to-use package.
Matt

**Comment by lucashusted** [comment]
Hi Matt, thanks for reaching out. This has been fixed. The package was updated by a different user and I hadn't gotten around to uploading to pypi. Should work now with version 0.0.8

**Comment by mattwood-astro** [comment]
Great - thanks so much!

Hope you’re doing well.

Cheers,
Matt

Matt A. Wood, Ph.D.
Regents Professor of Physics & Astronomy
Texas A&M University-Commerce
Commerce, TX 75429
O: 903.886.5486     M: 903.269.6682

On May 4, 2024, at 9:12 AM, Lucas Husted ***@***.***> wrote:

**External Email**



Hi Matt, thanks for reaching out. This has been fixed. The package was updated by a different user and I hadn't gotten around to uploading to pypi. Should work now with version 0.0.8

**Comment by javier-garcia-tilburg** [comment]
This problem persists in version `0.0.8` when using `addrows`, the traceback points to

https://github.com/lucashusted/pystout/blob/a6f6d6f25378fcb6d3a127d5a3c2f6bd8a26f809/pystout/pystout.py#L368
